### ISSUE TITLE
Command not working

### ISSUE THREAD

**Issue by cookiescrumbs** [amisarca/Sublime-Text-2-Table-Cleaner#2]
I'm trying to clean a table. I hi-light table and hit alt + ; and nothing happens. 
Any tips? Please.

**Comment by cookiescrumbs** [comment]
Sorted this problem and thought I'd leave it for others. 
If you install the Sublime Text 2 Cucumber bundle, Table Clean isn't recognised by Sublime. You need to move the Table clean folder out of the Cucumber bundle and into the package folder and restart Sublime Text 2. 

Then "alt + ;" will clean those messy tables.

**Comment by amisarca** [comment]
Hi @cookiescrumbs, thanks for pointing out this aspect, I will have a look and try to solve the issue.
