### ISSUE TITLE
Consider aligning end of row characters (\\) in LaTeX tables

### ISSUE THREAD

**Issue by nunoh** [amisarca/Sublime-Text-2-Table-Cleaner#5]
Hi, thanks for such a great plugin. 

Here goes a little suggestion. Why not also align the \\ of each row in LaTeX tables, so that it looks even cleaner?

as it is:

```
c1   & c2   & c3 \\   
c10  & c20  & c30 \\  
c100 & c200 & c300 \\ 
```

with suggestion improvement:

```
c1   & c2   & c3   \\   
c10  & c20  & c30  \\  
c100 & c200 & c300 \\ 
```

**Comment by amisarca** [comment]
Hi @nunoh,

Thanks for the suggestion. Will try implement it as soon as possible.

**Comment by nunoh** [comment]
Thank you. Glad to hear that.
