### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by brian-mann** [amisarca/Sublime-Text-2-Table-Cleaner#7]
I understand this is a ST2 bundle, but is getting this working on ST3 on the radar? Just wondering, thanks!

Specifically neither the table cleaner nor formatter works.

**Comment by amisarca** [comment]
Hi @brian-mann, thanks for pointing this out. I am planning to adapt the plugin in order to make it work on ST3.

**Comment by amisarca** [comment]
I created another repo for the Sublime Text 3 package, which can be found [here](https://github.com/amisarca/Sublime-Text-Table-Cleaner).
